Fix TypeError « Cannot read property 'y' of undefined
romi/3d-plantviewer pull request #106
Opened 2021-03-24 09:33 UTC by jcharlaix

2021-03-25 14:23 UTC, fabfabBesnard approved these changes
PR validated !

The changes fix the issue on at least one dataset analysis:
-dataset 2018-12-10_14-12-59 (Ler0_19_10_2018_A)
-analysis with plant-3d-vision v0.9 / geom pipe / config file = geom_pipe_real.toml modified with stem_axis_inverted = true in task [TreeGraph] + [AnglesAndInternodes]
-Ground truth (manual) measure has 30 intervals (31 fruits); analysis finds 31 interval / 32 fruits (Julie identified that the error typically occurs when nber of computed measure > nb manual measures)
-Plant-3d-explorer -> with current master, error "Cannot read property 'y' of undefined"
                             -> with this branch: everything works well !

![image](https://user-images.githubusercontent.com/20174786/112488479-db068c80-8d7d-11eb-9985-7d2b619bcf43.png)

2021-03-26 09:47 UTC, naittaleb requested changes

2021-03-26 09:47 UTC, naittaleb commented on src/Viewer/Panels/Graph/graph.js
> +  const nb = vertiaclTickNb - 1
Could you expalin by a brief comment why do you substract 1 to nb?

2021-03-26 09:47 UTC, naittaleb commented on src/Viewer/Panels/index.js
> +    // ? tempFruitPoints.slice(0, tempFruitPoints.length - 1)
If these code lines are useless. You can just remove them

2021-03-26 09:47 UTC, naittaleb commented on src/Viewer/Panels/index.js
> +    // ? tempAutomatedAngles.slice(0, tempAutomatedAngles.length - 1)
same comment

2021-03-26 09:47 UTC, naittaleb commented on src/Viewer/Panels/index.js
> +    // ? tempAutomatedInternodes.slice(0, tempAutomatedInternodes.length - 1)
same

2021-03-29 13:52 UTC, fabfabBesnard commented
ben du coup, on la merge celle-là ? C'est bon pour vous Julie et Nabil ?

2021-03-30 09:55 UTC, naittaleb approved these changes

2021-03-30 09:55 UTC, merged